# Generated by Django 3.1.5 on 2021-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectdata',
            fields=[
                ('time', models.IntegerField(db_column='Time', primary_key=True, serialize=False)),
                ('projectName', models.CharField(db_column='ProjectName', max_length=100)),
                ('days', models.IntegerField(db_column='Days')),
                ('man', models.IntegerField(db_column='Man')),
                ('manDay', models.IntegerField(db_column='ManDay')),
                ('bugNumber', models.IntegerField(db_column='BugNumber')),
                ('bugRate', models.FloatField(db_column='BugRate')),
                ('content', models.CharField(db_column='Content', max_length=100)),
            ],
            options={
                'db_table': 'project_data',
                'managed': True,
            },
        ),
    ]
