# Generated by Django 3.1.5 on 2021-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='time',
            field=models.CharField(db_column='Time', max_length=100, primary_key=True, serialize=False),
        ),
    ]
